export const products = [
  {
    id: 1,
    title: 'Essence Mascara Lash Princess',
    price: 9.99,
    url: 'https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png',
    category: 'beauty',
  },
  {
    id: 2,
    title: 'Eyeshadow Palette with Mirror',
    price: 19.99,
    url: 'https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png',
    category: 'beauty',
  },
  {
    id: 3,
    title: 'Powder Canister',
    price: 14.99,
    url: 'https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png',
    category: 'beauty',
  },
  {
    id: 4,
    title: 'Red Lipstick',
    price: 12.99,
    url: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png',
    category: 'beauty',
  },
  {
    id: 5,
    title: 'Red Nail Polish',
    price: 8.99,
    url: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png',
    category: 'beauty',
  },
  {
    id: 6,
    title: 'Calvin Klein CK One',
    price: 49.99,
    url: 'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png',
    category: 'fragrances',
  },
  {
    id: 7,
    title: 'Chanel Coco Noir Eau De',
    price: 129.99,
    url: 'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png',
    category: 'fragrances',
  },
  {
    id: 8,
    title: "Dior J'adore",
    price: 89.99,
    url: "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
    category: 'fragrances',
  },
  {
    id: 9,
    title: 'Dolce Shine Eau de',
    price: 69.99,
    url: 'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/1.png',
    category: 'fragrances',
  },
  {
    id: 10,
    title: 'Gucci Bloom Eau de',
    price: 79.99,
    url: 'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/1.png',
    category: 'fragrances',
  },
  {
    id: 11,
    title: 'Annibale Colombo Bed',
    price: 1899.99,
    url: 'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png',
    category: 'furniture',
  },
  {
    id: 12,
    title: 'Annibale Colombo Sofa',
    price: 2499.99,
    url: 'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png',
    category: 'furniture',
  },
  {
    id: 13,
    title: 'Bedside Table African Cherry',
    price: 299.99,
    url: 'https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/1.png',
    category: 'furniture',
  },
  {
    id: 14,
    title: 'Knoll Saarinen Executive Conference Chair',
    price: 499.99,
    url: 'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/1.png',
    category: 'furniture',
  },
  {
    id: 15,
    title: 'Wooden Bathroom Sink With Mirror',
    price: 799.99,
    url: 'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/1.png',
    category: 'furniture',
  },
  {
    id: 16,
    title: 'Apple',
    price: 1.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Apple/1.png',
    category: 'groceries',
  },
  {
    id: 17,
    title: 'Beef Steak',
    price: 12.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/1.png',
    category: 'groceries',
  },
  {
    id: 18,
    title: 'Cat Food',
    price: 8.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/1.png',
    category: 'groceries',
  },
  {
    id: 19,
    title: 'Chicken Meat',
    price: 9.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/1.png',
    category: 'groceries',
  },
  {
    id: 20,
    title: 'Cooking Oil',
    price: 4.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/1.png',
    category: 'groceries',
  },
  {
    id: 21,
    title: 'Cucumber',
    price: 1.49,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png',
    category: 'groceries',
  },
  {
    id: 22,
    title: 'Dog Food',
    price: 10.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/1.png',
    category: 'groceries',
  },
  {
    id: 23,
    title: 'Eggs',
    price: 2.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Eggs/1.png',
    category: 'groceries',
  },
  {
    id: 24,
    title: 'Fish Steak',
    price: 14.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/1.png',
    category: 'groceries',
  },
  {
    id: 25,
    title: 'Green Bell Pepper',
    price: 1.29,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/1.png',
    category: 'groceries',
  },
  {
    id: 26,
    title: 'Green Chili Pepper',
    price: 0.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/1.png',
    category: 'groceries',
  },
  {
    id: 27,
    title: 'Honey Jar',
    price: 6.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/1.png',
    category: 'groceries',
  },
  {
    id: 28,
    title: 'Ice Cream',
    price: 5.49,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/1.png',
    category: 'groceries',
  },
  {
    id: 29,
    title: 'Juice',
    price: 3.99,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Juice/1.png',
    category: 'groceries',
  },
  {
    id: 30,
    title: 'Kiwi',
    price: 2.49,
    url: 'https://cdn.dummyjson.com/products/images/groceries/Kiwi/1.png',
    category: 'groceries',
  },
];
